{% set name = "torchgan" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d86c1321a119ac724308f92c6921fafa40dd20e36ebc5bbef3488acf25d9a098

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - setuptools

  host:
    - python >=3
    - pip
    - torchvision
    - numpy >=1.11
    - pytorch

  run:
    - python >=3
    - torchvision
    - numpy >=1.11
    - pytorch

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - torchgan
    - torchgan.layers
    - torchgan.logging
    - torchgan.losses
    - torchgan.metrics
    - torchgan.models
    - torchgan.trainer
  commands:
    - pytest --verbose

about:
  home: https://github.com/torchgan/torchgan
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Research Framework for easy and efficient training of GANs based on Pytorch'
  doc_url: http://torchgan.readthedocs.io/
  dev_url: https://github.com/torchgan/torchgan

extra:
  recipe-maintainers:
    - avik-pal
    - Aniket1998
